export default {
    USER_SIGNUP_START : "USER_SIGNUP_START",
    USER_SIGNUP_SUCCESS : "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAILURE : "USER_SIGNUP_FAILURE",
    USER_LOGIN_START : "USER_LOGIN_START",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE : "USER_LOGIN_FAILURE",
    USER_LOGOUT_START : "USER_LOGOUT_START",
    USER_LOGOUT_SUCCESS : "USER_LOGOUT_SUCCESS",
    USER_LOGOUT_FAILURE : "USER_LOGGOUT_FAILURE",
    USER_UPDATE_START : "USER_UPDATE_START",
    USER_UPDATE_SUCCESS : "USER_UPDATE_SUCCESS",
    USER_UPDATE_FAILURE : "USER_UPDATE_FAILURE",
    USER_UPDATE_AVATAR_START : "USER_UPDATE_AVATAR_START",
    USER_UPDATE_AVATAR_SUCCESS : "USER_UPDATE_AVATAR_SUCCESS",
    USER_UPDATE_AVATAR_FAILURE : "USER_UPDATE_AVATAR_FAILURE",
    HIDE_ERROR_MESSAGE : "HIDE_ERROR_MESSAGE"
}