export default {
  FETCH_USER_COLLECTION_START: "FETCH_USER_COLLECTION_START",
  FETCH_USER_COLLECTION_SUCCESS: "FETCH_USER_COLLECTION_SUCCESS",
  FETCH_USER_COLLECTION_FAILURE: "FETCH_USER_COLLECTION_FAILURE",
};
